export const projectsData = [
  {
    id: 1,
    title: 'Crwn Clothing',
    description: 'Cloth Shop',
    image: '/images/projects//img-1.jpg',
    tag: ['All', 'React'],
    gitUrl: 'https://github.com/Kviatkovski/Crwn-Clothing',
    previewUrl: 'https://lukas-crwn-clothing.netlify.app/',
  },
  {
    id: 2,
    title: 'Monster Rolodexs',
    description: 'Monster Filter',
    image: '/images/projects//img-2.jpg',
    tag: ['All', 'React'],
    gitUrl: 'https://github.com/Kviatkovski/Monsters-Rolodex',
    previewUrl: 'https://lukas-monsters-rolodex.netlify.app/',
  },
  {
    id: 3,
    title: 'Todo App',
    description: "Add And Remove Todo's",
    image: '/images/projects//img-3.jpg',
    tag: ['All', 'React'],
    gitUrl: 'https://github.com/Kviatkovski/Todo-App',
    previewUrl: 'https://lukas-todo-app.netlify.app/',
  },
  {
    id: 4,
    title: 'Internship Project',
    description: 'Internship Project',
    image: '/images/projects//img-4.jpg',
    tag: ['All', 'React'],
    gitUrl: 'https://github.com/Kviatkovski/Intership-Project',
    previewUrl: 'https://lukas-intershi-project.netlify.app/',
  },
  {
    id: 5,
    title: 'Pong',
    description: 'Play Classic Pong Game',
    image: '/images/projects//img-5.jpg',
    tag: ['All', 'Js'],
    gitUrl: 'https://github.com/Kviatkovski/Pong',
    previewUrl: 'https://lukas-pong.netlify.app/',
  },
  {
    id: 6,
    title: 'Paint Clone',
    description: 'Paint Something',
    image: '/images/projects//img-6.jpg',
    tag: ['All', 'Js'],
    gitUrl: 'https://github.com/Kviatkovski/Paint-Clone',
    previewUrl: 'https://lukas-paint-clone.netlify.app/',
  },
  {
    id: 7,
    title: 'Calculator',
    description: 'Basic Calculator',
    image: '/images/projects//img-7.jpg',
    tag: ['All', 'Js'],
    gitUrl: 'https://github.com/Kviatkovski/Calculator',
    previewUrl: 'https://lukas-calculator.netlify.app/',
  },
  {
    id: 8,
    title: 'Math Sprint Game',
    description: 'Math Related Game',
    image: '/images/projects//img-8.jpg',
    tag: ['All', 'Js'],
    gitUrl: 'https://github.com/Kviatkovski/Math-Sprint-Game',
    previewUrl: 'https://lukas-math-sprint-game.netlify.app/',
  },
  {
    id: 9,
    title: 'Drag And Drop',
    description: 'Drag And Drop Items',
    image: '/images/projects//img-9.jpg',
    tag: ['All', 'Js'],
    gitUrl: 'https://github.com/Kviatkovski/Drag-And-Drop',
    previewUrl: 'https://lukas-drag-and-drop.netlify.app/',
  },
  {
    id: 10,
    title: 'Splash page',
    description: 'Page In Which You Can Change Background',
    image: '/images/projects//img-10.jpg',
    tag: ['All', 'Js'],
    gitUrl: 'https://github.com/Kviatkovski/Splash-Page',
    previewUrl: 'https://lukas-splash-page.netlify.app/',
  },
  {
    id: 11,
    title: 'NASA API Pictures',
    description: 'Read And Add To Favorites Nasa Researches',
    image: '/images/projects//img-11.jpg',
    tag: ['All', 'Js'],
    gitUrl: 'https://github.com/Kviatkovski/NASA-API-Pictures',
    previewUrl: 'https://lukas-nasa-api-pictures.netlify.app/',
  },
  {
    id: 12,
    title: 'Spock Rock Game',
    description: 'Play Some Rock Paper Scissors Lizard Spock Game',
    image: '/images/projects//img-12.jpg',
    tag: ['All', 'Js'],
    gitUrl: 'https://github.com/Kviatkovski/Spock-Rock-Game',
    previewUrl: 'https://lukas-spock-rock-game.netlify.app/',
  },
  {
    id: 13,
    title: 'Video Player',
    description: 'Watch Videos With Costume Player',
    image: '/images/projects//img-13.jpg',
    tag: ['All', 'Js'],
    gitUrl: 'https://github.com/Kviatkovski/Video-Player',
    previewUrl: 'https://lukas-video-player.netlify.app/',
  },
  {
    id: 14,
    title: 'Music Player',
    description: 'Listen To Some Music With Costume Player',
    image: '/images/projects//img-14.jpg',
    tag: ['All', 'Js'],
    gitUrl: 'https://github.com/Kviatkovski/Music-Player',
    previewUrl: 'https://lukas-music-player.netlify.app/',
  },
  {
    id: 15,
    title: 'Form Validation',
    description: 'This Page Validates Input Values',
    image: '/images/projects//img-15.jpg',
    tag: ['All', 'Js'],
    gitUrl: 'https://github.com/Kviatkovski/Form-Validation',
    previewUrl: 'https://lukas-form-validation.netlify.app/',
  },
  {
    id: 16,
    title: 'Book keeper',
    description: 'This Page Creates Bookmarks And Saves Them',
    image: '/images/projects//img-16.jpg',
    tag: ['All', 'Js'],
    gitUrl: 'https://github.com/Kviatkovski/Book-Keeper',
    previewUrl: 'https://lukas-book-keeper.netlify.app/',
  },
  {
    id: 17,
    title: 'Costume Countdown',
    description: 'This Page Sets Countdown',
    image: '/images/projects//img-17.jpg',
    tag: ['All', 'Js'],
    gitUrl: 'https://github.com/Kviatkovski/Costume-Countdown',
    previewUrl: 'https://lukas-costume-countdown.netlify.app/',
  },
  {
    id: 18,
    title: 'Picture In Picture',
    description: 'This Page lets The User Watch A Video In A Small Window',
    image: '/images/projects//img-18.jpg',
    tag: ['All', 'Js'],
    gitUrl: 'https://github.com/Kviatkovski/Picture-In-Picture',
    previewUrl: 'https://lukas-picture-in-picture.netlify.app/',
  },
  {
    id: 19,
    title: 'Infinite Scroll',
    description: 'Page WIth Infinite Loading Images',
    image: '/images/projects//img-19.jpg',
    tag: ['All', 'Js'],
    gitUrl: 'https://github.com/Kviatkovski/Infinite-Scroll',
    previewUrl: 'https://lukas-infinite-scroll.netlify.app/',
  },
  {
    id: 20,
    title: 'Joke Teller',
    description: 'Press The Button And Enjoy Some Jokes',
    image: '/images/projects//img-20.jpg',
    tag: ['All', 'Js'],
    gitUrl: 'https://github.com/Kviatkovski/Joke-Teller',
    previewUrl: 'https://lukas-joke-teller.netlify.app/',
  },
  {
    id: 21,
    title: 'Animated Navigation',
    description: 'Hamburger Menu Navigation',
    image: '/images/projects//img-21.jpg',
    tag: ['All', 'Js'],
    gitUrl: 'https://github.com/Kviatkovski/Animated-Navigation',
    previewUrl: 'https://lukas-animated-navigation.netlify.app/',
  },
  {
    id: 22,
    title: 'Animated Template',
    description: 'Page With Beautiful Animations',
    image: '/images/projects//img-22.jpg',
    tag: ['All', 'Js'],
    gitUrl: 'https://github.com/Kviatkovski/Animated-Tamplate',
    previewUrl: 'https://lukas-animated-template.netlify.app/',
  },
  {
    id: 23,
    title: 'Light And Dark Mode',
    description: 'Page With Light And Dark Themes',
    image: '/images/projects//img-23.jpg',
    tag: ['All', 'Js'],
    gitUrl: 'https://github.com/Kviatkovski/Light-Dark-Mode',
    previewUrl: 'https://lukas-light-dark-mode.netlify.app/',
  },
  {
    id: 24,
    title: 'Quote Generator',
    description: 'Generate Some Quotes And Shear Them On Twitter',
    image: '/images/projects//img-24.jpg',
    tag: ['All', 'Js'],
    gitUrl: 'https://github.com/Kviatkovski/Quote-Generator',
    previewUrl: 'https://lukas-quote-generator.netlify.app/',
  },
  {
    id: 25,
    title: 'Omnifood Template',
    description: 'Food Delivery Page',
    image: '/images/projects//img-25.jpg',
    tag: ['All', 'Html/Css'],
    gitUrl: 'https://github.com/Kviatkovski/Omnifood-Project',
    previewUrl: 'https://lukas-omnifood-site.netlify.app/',
  },
  {
    id: 26,
    title: 'Nexter',
    description: 'Property Shop Page',
    image: '/images/projects//img-26.jpg',
    tag: ['All', 'Html/Css'],
    gitUrl: 'https://github.com/Kviatkovski/Nexter-Project',
    previewUrl: 'https://lukas-nexte-project.netlify.app/',
  },
];
